// <auto-generated />
using System;
using ItauCompraProgramada.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItauCompraProgramada.Infrastructure.Migrations
{
    [DbContext(typeof(ItauDbContext))]
    [Migration("20260228115656_UpdateClientAndGraphicAccount")]
    partial class UpdateClientAndGraphicAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.BasketItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BasketId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Percentual");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("ItensCesta", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AdhesionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataAdesao");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<decimal>("MonthlyContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorMensal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nome");

                    b.Property<int>("NextPurchaseDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5)
                        .HasColumnName("DiaExecucao");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.Custody", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoMedio");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataUltimaAtualizacao");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Custodias", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.Distribution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DistributedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataDistribuicao");

                    b.Property<long>("FilhoteCustodyId")
                        .HasColumnType("bigint");

                    b.Property<long>("PurchaseOrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoUnitario");

                    b.HasKey("Id");

                    b.HasIndex("FilhoteCustodyId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("Distribuicoes", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.GraphicAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NumeroConta");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("Saldo");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("ContasGraficas", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.IREvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("BaseValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorBase");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataEvento");

                    b.Property<decimal>("IRValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorIR");

                    b.Property<bool>("PublishedToKafka")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("PublicadoKafka");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("EventosIR", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataExecucao");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TipoMercado");

                    b.Property<long>("MasterAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoUnitario");

                    b.HasKey("Id");

                    b.HasIndex("MasterAccountId");

                    b.ToTable("OrdensCompra", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.Rebalancing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RebalanceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataRebalanceamento");

                    b.Property<decimal>("SaleValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorVenda");

                    b.Property<string>("TickerBought")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TickerSold")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Rebalanceamentos", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.RecommendationBasket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCriacao");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataDesativacao");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("CestasRecomendacao", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.StockQuote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("ClosingPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoFechamento");

                    b.Property<decimal>("MaxPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoMaximo");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoMinimo");

                    b.Property<decimal>("OpeningPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoAbertura");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("TradingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataPregao");

                    b.HasKey("Id");

                    b.ToTable("Cotacoes", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.StoredEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.ToTable("stored_events", (string)null);
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.BasketItem", b =>
                {
                    b.HasOne("ItauCompraProgramada.Domain.Entities.RecommendationBasket", "Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.Custody", b =>
                {
                    b.HasOne("ItauCompraProgramada.Domain.Entities.GraphicAccount", "Account")
                        .WithMany("Custodies")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.Distribution", b =>
                {
                    b.HasOne("ItauCompraProgramada.Domain.Entities.Custody", "Custody")
                        .WithMany()
                        .HasForeignKey("FilhoteCustodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItauCompraProgramada.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Custody");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.GraphicAccount", b =>
                {
                    b.HasOne("ItauCompraProgramada.Domain.Entities.Client", "Client")
                        .WithOne("GraphicAccount")
                        .HasForeignKey("ItauCompraProgramada.Domain.Entities.GraphicAccount", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.IREvent", b =>
                {
                    b.HasOne("ItauCompraProgramada.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("ItauCompraProgramada.Domain.Entities.GraphicAccount", "MasterAccount")
                        .WithMany()
                        .HasForeignKey("MasterAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterAccount");
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.Rebalancing", b =>
                {
                    b.HasOne("ItauCompraProgramada.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.Client", b =>
                {
                    b.Navigation("GraphicAccount");
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.GraphicAccount", b =>
                {
                    b.Navigation("Custodies");
                });

            modelBuilder.Entity("ItauCompraProgramada.Domain.Entities.RecommendationBasket", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
